---
title: "Standard Deviation"
output: html_notebook
---
```{r message=FALSE, warning=FALSE, error=TRUE}
library(readr)
library(dplyr)
```

```{r error=TRUE}
load("project.Rda")
```

```{r error=TRUE}
# Change these variables to be the standard deviation of each dataset.
# Inspect Data
head(london_data)
print(nrow(london_data))

temp <- london_data$TemperatureC
average_temp <- mean(temp)
print(average_temp)

# Variance and SD for the year
temperature_var <- var(temp)
print(temperature_var)

temperature_standard_deviation <- sd(temp)
print(temperature_standard_deviation)

#Inspect once again
head(london_data)

# Get monthly temperature average
june <- london_data %>% filter(month == '06')
july <- london_data %>% filter(month == '07')

june_mean_temp <- mean(june$TemperatureC)
print(june_mean_temp)
july_mean_temp <- mean(july$TemperatureC)
print(july_mean_temp) 

print(sd(june$TemperatureC))
print(sd(july$TemperatureC))

# Analyze by month
monthly_stats <- london_data %>% group_by(month) %>% summarize(mean = mean(TemperatureC), standard_deviation = sd(TemperatureC))

print(monthly_stats)

```
